# 正则化

### L1正则化与L2正则化的区别

1，L1正则化，会使某些参数为0，有吸收性，带来特征的选择，L2不会  
2，图中L1是正方形，L2是圆形  
3，L1绝对值、L2平方  
4，L1可以做参数的选择

# 支持向量机

1，找到两个支持向量，距离超平面距离最远  
2，不可分：升维，核方法（一般选择高斯核）  
软方法、硬方法（核函数选择）  
n：特征数量， m：样本数量  
1，n~ & n > m ：逻辑回归、 没有核SVM  
2，n_, m-: SVM with kernel  
3，n_, m~: add more features  
4，SVM not so good for large of samples  
5，NN can handle Always  

优点：  
1，中小样本  
2，可解释性强  

缺点：  
1，计算复杂度高    
2，需要调节核  

顺口溜：  
1，高维用线性  
2，低维试线性  
3，不行用高斯  

在SVM中正则系数：  
1，C大过拟合  
2，C小欠拟合  


# softmax

1，分数矩阵进来， e的幂操作  
2，归一化， 除以 所有分数e的幂的和  
3，求损失值， loss = -log（x）x为正确类别  
4，偏移：第一步作偏移 每个数据减去矩阵最大项  

In [2]:
import numpy as np

In [3]:
def softmax(x):
    exps = np.exp(x)
    return np.exp(x) / np.sum(exps)

In [4]:
softmax(np.array([2,3,4]))

array([0.09003057, 0.24472847, 0.66524096])

In [6]:
def real_softmax(x):
    shift_x = x - np.max(x) # 减去一个偏移值
    return softmax(shift_x)

In [12]:
real_softmax(np.array([2,3,4]))

array([0.09003057, 0.24472847, 0.66524096])

In [13]:
real_softmax(np.array([1000,2000,2330]))



array([0.00000000e+000, 4.81749166e-144, 1.00000000e+000])

# 无监督学习


1，聚类  
2，降维
 
### K-Means  
1，先选择2个初始点  
2，点到初始点到距离近的归类初试点类  
3，移动初试点  
4，在重复2，3步骤，直到初始点不再移动  

### kNN k近邻 （监督学习）
1，没有模型，抄袭现有的数据点，最相近点数据点  
2，k参数：最相近点k个点的标签值投票决定预测点的标签


# 过拟合 欠拟合

偏差(Bias)：训练模型的预测情况  
方差(Variance)：新数据的预测情况

画图：  
1，error/ 复杂度   
2，error/ 正则系数


