In [1]:
import torch

In [2]:
a = torch.empty(5,3)
a

tensor([[0.0000e+00, 2.5244e-29, 0.0000e+00],
        [2.5244e-29, 4.5036e+16, 4.5891e-41],
        [4.5212e+16, 4.5891e-41, 9.1624e+16],
        [4.5891e-41, 9.1625e+16, 4.5891e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
a = torch.rand(3,3)

In [4]:
a

tensor([[0.1551, 0.5197, 0.8950],
        [0.6641, 0.5146, 0.3308],
        [0.7671, 0.2130, 0.7745]])

In [5]:
a.dtype


torch.float32

In [6]:
a = torch.tensor([5,3])
a

tensor([5, 3])

In [7]:
a = a.new_ones(5,3)

In [8]:
a

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [10]:
b = torch.randn_like(a, dtype=torch.float)
b

tensor([[-1.3457,  1.4979,  0.5092],
        [-0.8770,  0.4985, -1.1250],
        [-1.9603, -0.4960,  1.7117],
        [ 0.0112,  0.2112,  0.0943],
        [-0.4114, -0.6250,  0.0588]])

In [11]:
b.shape

torch.Size([5, 3])

In [13]:
b.size()

torch.Size([5, 3])

In [17]:
c = torch.arange(9).reshape(3,3)

In [18]:
c

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
c.view(9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
c

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [22]:
a = c.view(9)

In [23]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a.grad

In [31]:
import numpy as np

In [41]:
N, D_in, H, D_out = 64, 1000, 100, 10


In [44]:
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

l = 1e-6

for it in range(500):
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    
    # compute loss
    loss = np.square(y_pred - y).sum()
    print(it, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    w1 -= l * grad_w1
    w2 -= l * grad_w2
    

0 31782490.84776744
1 32874316.50947191
2 39480200.41511234
3 43808063.06674564
4 38394125.09032567
5 23980616.91481995
6 11228600.289973363
7 4749504.671887663
8 2359442.3163579246
9 1500457.229420456
10 1133845.0474635994
11 928537.5552468299
12 786280.1189433441
13 675936.479805172
14 586053.9492437374
15 511154.30651079153
16 448001.5731074206
17 394475.2807865023
18 348690.8242354236
19 309306.69705367635
20 275230.2276803929
21 245630.95654942637
22 219804.99111222784
23 197182.65883805972
24 177311.93153614787
25 159846.24066554112
26 144405.1898131962
27 130700.91980516454
28 118510.28392792324
29 107648.96309927295
30 97948.41897366129
31 89261.6889634885
32 81478.27797832908
33 74489.62966864911
34 68198.2873260086
35 62519.60821467811
36 57396.38685221712
37 52760.7700630193
38 48555.85080232244
39 44737.91997699311
40 41265.53419533675
41 38116.228641370384
42 35252.92112814999
43 32640.79343817533
44 30253.59050826759
45 28070.619694452285
46 26069.253993839477
47 24232.78

In [38]:
import numpy as np

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10


# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    
    # loss = (y_pred - y) ** 2
    grad_y_pred = 2.0 * (y_pred - y)
    # 
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 34029098.20785901
1 28327529.286202136
2 25198985.561848875
3 21165898.8660159
4 15982424.265181433
5 10789220.8027098
6 6784685.216454179
7 4184933.378474255
8 2661311.73332985
9 1795142.302863257
10 1294100.250338194
11 988998.9277855998
12 790014.0260108977
13 650854.7012714611
14 547446.256055794
15 467010.01122655044
16 402342.5345227994
17 349179.50459482876
18 304797.180086375
19 267423.56764794595
20 235579.41585731736
21 208258.92971410073
22 184690.4172529775
23 164258.58358242176
24 146461.69401297832
25 130902.327120658
26 117251.06775162296
27 105241.53173915998
28 94654.42747544406
29 85286.86075705125
30 76976.77680123654
31 69585.54626139863
32 62998.935977146044
33 57119.080584079784
34 51855.22186773147
35 47137.77052496301
36 42901.76581168402
37 39092.71739696649
38 35676.674318242
39 32596.184163571557
40 29812.279889410132
41 27293.224000837195
42 25010.188884742827
43 22937.92881692147
44 21054.700202004657
45 19342.02188515587
46 17782.976580689046
47 16363.15

In [45]:
x = torch.empty(5,3)
x

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [46]:
y = torch.rand(5,3)

In [47]:
x + y

tensor([[0.3859, 0.6741, 0.8760],
        [0.9284, 0.5427, 0.5447],
        [0.2597, 0.3629, 0.2919],
        [0.5440, 0.0099, 0.1426],
        [0.2409, 0.9705, 0.7499]])

In [48]:
y.t_()

tensor([[0.3859, 0.9284, 0.2597, 0.5440, 0.2409],
        [0.6741, 0.5427, 0.3629, 0.0099, 0.9705],
        [0.8760, 0.5447, 0.2919, 0.1426, 0.7499]])

In [49]:
y

tensor([[0.3859, 0.9284, 0.2597, 0.5440, 0.2409],
        [0.6741, 0.5427, 0.3629, 0.0099, 0.9705],
        [0.8760, 0.5447, 0.2919, 0.1426, 0.7499]])

In [50]:
y.t()

tensor([[0.3859, 0.6741, 0.8760],
        [0.9284, 0.5427, 0.5447],
        [0.2597, 0.3629, 0.2919],
        [0.5440, 0.0099, 0.1426],
        [0.2409, 0.9705, 0.7499]])

In [51]:
y.T

tensor([[0.3859, 0.6741, 0.8760],
        [0.9284, 0.5427, 0.5447],
        [0.2597, 0.3629, 0.2919],
        [0.5440, 0.0099, 0.1426],
        [0.2409, 0.9705, 0.7499]])

In [52]:
y

tensor([[0.3859, 0.9284, 0.2597, 0.5440, 0.2409],
        [0.6741, 0.5427, 0.3629, 0.0099, 0.9705],
        [0.8760, 0.5447, 0.2919, 0.1426, 0.7499]])

In [53]:
y.t

<function Tensor.t>

In [54]:
y


tensor([[0.3859, 0.9284, 0.2597, 0.5440, 0.2409],
        [0.6741, 0.5427, 0.3629, 0.0099, 0.9705],
        [0.8760, 0.5447, 0.2919, 0.1426, 0.7499]])

In [55]:
y.t

<function Tensor.t>

In [56]:
y

tensor([[0.3859, 0.9284, 0.2597, 0.5440, 0.2409],
        [0.6741, 0.5427, 0.3629, 0.0099, 0.9705],
        [0.8760, 0.5447, 0.2919, 0.1426, 0.7499]])

In [57]:
y.t()

tensor([[0.3859, 0.6741, 0.8760],
        [0.9284, 0.5427, 0.5447],
        [0.2597, 0.3629, 0.2919],
        [0.5440, 0.0099, 0.1426],
        [0.2409, 0.9705, 0.7499]])

In [58]:
y[:,1]

tensor([0.9284, 0.5427, 0.5447])

In [59]:
y

tensor([[0.3859, 0.9284, 0.2597, 0.5440, 0.2409],
        [0.6741, 0.5427, 0.3629, 0.0099, 0.9705],
        [0.8760, 0.5447, 0.2919, 0.1426, 0.7499]])

In [61]:
x = torch.randn(4, 4)

In [62]:
x.item

<function Tensor.item>

In [63]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [64]:
a.add_(2)
a

AttributeError: 'numpy.ndarray' object has no attribute 'add_'

In [65]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [66]:
b.add_(3)

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)

In [67]:
b.matmul_(2)

AttributeError: 'Tensor' object has no attribute 'matmul_'

In [69]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [70]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [71]:
y.grad_fn


In [74]:
print(x.grad_fn)

None


In [84]:
z = y * y * 3
out = z.mean()

out

tensor(27., grad_fn=<MeanBackward0>)

In [86]:
out.backward()
x.grad
y.backward()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [81]:
a = torch.randn(2, 3)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)


False
True


In [105]:
x = torch.arange(4.)
x.requires_grad_(True)
y = x* x+ 3
z = y.sum()
z
y

tensor([ 3.,  4.,  7., 12.], grad_fn=<AddBackward0>)

In [103]:
z.backward()

In [104]:
x.grad

tensor([0., 2., 4., 6.])

In [106]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([  725.8818,   311.6635, -1158.4136], grad_fn=<MulBackward0>)


In [149]:
dtype = torch.float
device = torch.device('cpu')

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)
learning_rate = 1e-6

In [150]:
print(x.shape)
print(y.shape)

torch.Size([64, 1000])
torch.Size([64, 10])


In [151]:
w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)
print(w1.shape)
print(w2.shape)

torch.Size([1000, 100])
torch.Size([100, 10])


In [153]:
for t in range(500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())
    
    loss.backward()
        
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()
        

    

99 185.01754760742188
199 0.21314485371112823
299 0.0006823792355135083
399 4.681038626586087e-05
499 1.5293464457499795e-05


In [137]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.9384, -0.3983, -0.2297], requires_grad=True)

In [138]:
y = x * 2

In [139]:
y

tensor([ 1.8769, -0.7965, -0.4594], grad_fn=<MulBackward0>)

In [141]:
y.data.norm()

tensor(2.0900)

### 神经网络

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        