In [1]:
import numpy as np

In [52]:
def Iou(box, boxes):
    
    box_area = box[2] * box[3]
    area = boxes[:, 2] * boxes[:, 3]
    
    w_min = np.where(box[0] < boxes[:, 0], box[2], boxes[:, 2])
    h_min = np.where(box[1] < boxes[:, 1], box[3], boxes[:, 3])
    w = w_min - np.abs(box[0] - boxes[:, 0])
    h = h_min - np.abs(box[1] - boxes[:, 1])
    
    w = np.where(w < 0, 0, w)
    h = np.where(h < 0, 0, h)
    
    inter = w * h
    ovr = np.true_divide(inter, (box_area + area - inter))
    
    return ovr

In [53]:
boxes = np.array(
[[ 69,359 ,50  ,36],
 [227, 382 , 56 , 43],
 [296, 305,  44 , 26],
 [353, 280 , 40 , 36],
 [885 ,377  ,63 , 41],
 [819 ,391  ,34 , 43],
 [727 ,342  ,37  ,31],
 [598 ,246 , 33 , 29],
 [740, 308  ,45,  33]])
box =  [885 ,377 , 63 , 41]

In [54]:
o = Iou(box, boxes)

[18 36  0  0 41 27  0  0  0]


In [56]:
b = np.array(box)

In [63]:
landmark_ = np.arange(12).reshape(-1, 4)
landmark_

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
landmark_[[0, 1]] = landmark_[[1, 0]]

In [70]:
landmark_[0, :]

array([4, 5, 6, 7])